# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install dependencies
      run: yarn
    - name: Prettier check
      run: yarn prettier:check
    - name: ESLint check
      run: yarn eslint
    - name: Svelte check
      run: yarn validate
    - name: Typescript check
      run: yarn typecheck
